steps:
  - name: 'docker/compose:1.29.2'
    args: [ 'up', '-d' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'movie-app-frontend:latest', 'gcr.io/$PROJECT_ID/movie-search-app' ]
images: [ 'gcr.io/$PROJECT_ID/movie-search-app' ]